### ISSUE TITLE
No adjustment of Pixel Threshold

### ISSUE THREAD

**Issue by gogogadget** [kif-framework/Lela#12]
Currently there is no ability to adjust the pixel threshold for image comparison. 

Ideally this would be exposed as an option as demonstrated in this commit (on @Oleg-Ivanov 's fork) here https://github.com/kif-framework/Lela/commit/10485a9c9636421c06028bc950a614da1d3d1546 .

**Comment by phatmann** [comment]
Please submit a pull request for this and I will merge it in.

**Comment by glentregoning** [comment]
I think this can be resolved now this is merged in, although it would also be good to get a new Lela release if we could?

**Comment by phatmann** [comment]
Thanks @glentregoning. I will do a new release ASAP, especially now that we have compatibility with KIF 3.3.
