### ISSUE TITLE
imageWithContentsOfFile can't find the filepath error - expectScreenToMatchImageNamed

### ISSUE THREAD

**Issue by UXDart** [kif-framework/Lela#13]
Hello. For some reason [imageWithContentsOfFile:] doesn't find the path file image, but using NSData it works, is anyone else having this problem? is anyone using Lela? :)
```
+ (UIImage *)expectedImageWithName:(NSString *)name
{
    NSString *fileName = [[self imageNameForScreenNamed:name] stringByAppendingPathExtension:@"png"];
    NSString *filePath = [[self directoryForExpectedImages] stringByAppendingPathComponent:fileName];
    NSData *data = [NSData dataWithContentsOfFile:filePath]; //I changed these next 2 lines
    return [UIImage imageWithData:data];
}
```
can you change it? I'm using cocoapods!

note: using iOS 8.3 with ipad 2 simulator

TIA!

**Comment by UXDart** [comment]
oh... I saw it is fixed in the latest branch, can you push it to cocoapods? Thanks!

**Comment by phatmann** [comment]
Pushed!

**Comment by UXDart** [comment]
Thanks!!
