### ISSUE TITLE
Location of expected images is where?

### ISSUE THREAD

**Issue by kenny-va** [kif-framework/Lela#14]
Hello, I'm simply stumped on where to put the expected images in order to pass the test.  The documentation states, "copy the images into your test bundle" ... but I'm too noob to know where/how to do that.

**Comment by phatmann** [comment]
In your Xcode project, you will see a group for YourApp and one for YourAppTests. Drag your images into  YourAppTests. In the dialog, check "YourAppTests" in the Add to Targets section.

**Comment by kenny-va** [comment]
Thank you, I’ll give it a shot.

The way I fixed it (for now) was to modify this routine.  I added the images as a folder to the project.  

+ (NSString *)directoryForExpectedImages
{
    return [[NSBundle mainBundle] resourcePath];
    //return [[NSBundle bundleForClass:self] resourcePath];
}
