### ISSUE TITLE
Is Lela friendly with iOS9 and Xcode7?

### ISSUE THREAD

**Issue by kenny-va** [kif-framework/Lela#15]
Just curious, because we ported our app to Xcode7 and I'm having some interesting referential/dependency errors.

ld: warning: directory not found for option '-L/Users/klucas/Documents/Gannett/GIT/akira-ios/build/Debug-iphoneos'
  "_OBJC_CLASS_$_KIFTestCase", referenced from:
      _OBJC_CLASS_$_Lela_Visual_Tests in Lela_Visual_Tests.o
  "_OBJC_CLASS_$_KIFUITestActor", referenced from:
      objc-class-ref in Lela_Visual_Tests.o
  "_OBJC_METACLASS_$_KIFTestCase", referenced from:
      _OBJC_METACLASS_$_Lela_Visual_Tests in Lela_Visual_Tests.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by phatmann** [comment]
Which version of KIF are you using?

**Comment by kenny-va** [comment]
We are trying a few things here so I'm going to close this ticket.  Will re-open later if this continues to be an issue.
