### ISSUE TITLE
Support KIF 3.3.0

### ISSUE THREAD

**Issue by glentregoning** [kif-framework/Lela#16]
Currently Lela doesn't support KIF 3.3.0 as the XCTest and OCTest sub-specs have been removed.

**Comment by phatmann** [comment]
Thanks for the bug report. Will fix ASAP.

**Comment by phatmann** [comment]
Fixed by #18

**Comment by phatmann** [comment]
I am having issues getting Lela to pass Podspec lint. When I solve them I will push the release. Hopefully today.

**Comment by phatmann** [comment]
Release 0.3.0 has been pushed to CocoaPods
