### ISSUE TITLE
Lela + use_frameworks!

### ISSUE THREAD

**Issue by mrdekk** [kif-framework/Lela#20]
For some reason (I have Swift only framework in tests) I use use_frameworks! in cocoapods, so Lela is getting compiled to its own .framework
So this function
``` objc
+ (NSString *)directoryForExpectedImages
{
    return [[NSBundle bundleForClass:self] resourcePath];
} 
```
returns path for Lela.framework, not the testing target
but I have no means to override this from my test

**Comment by mrdekk** [comment]
Update: Interesting, but if I direct cocoapods to master branch, it works

**Comment by mrdekk** [comment]
but #19 seems to fix it better, and I think master works because of this

**Comment by justinseanmartin** [comment]
Is this needed if #19 fixes the same issue? Or are you just looking for a release with that fix in it?

**Comment by mrdekk** [comment]
Release would be good, but as for cocoapods I can use with a master branch.
I think issue can be closed

**Comment by justinseanmartin** [comment]
Will create a release.

**Comment by justinseanmartin** [comment]
Done.
