### ISSUE TITLE
iOS 8 issues in simulator

### ISSUE THREAD

**Issue by markguinn** [kif-framework/Lela#9]
The same test run on the ios7.0 simulator works but on the ios8 simulator fails to find the reference image. The following call seems to return nil on Lela.mm line 68:

```
    return [UIImage imageWithContentsOfFile:filePath];
```

I suspect it's related to this issue: http://stackoverflow.com/questions/25884382/ios-8-bundle-path-changes

**Comment by patoroco** [comment]
What about that? I have "similar" problem.
